//#############################################
//## file: AnalizadorSintactico.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for AnalizadorSintactico: AnalizadorSintactico
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */

package compilador;

public class cacaVal
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval;

/**
 * object value of this 'union'
 */
public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public cacaVal()
{
}
/**
 * Initialize me as an int
 */
public cacaVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public cacaVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public cacaVal(String val)
{
  sval=val;
}

/**
 * Initialize me as an Object
 */
public cacaVal(Object val)
{
  obj=val;
}
}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
